### ISSUE TITLE
JavaScript To-Do List

### ISSUE THREAD

**Issue by Zyzzx201** [Minawasfy/Software-Project#3]
Misc task: i uploaded the footer as a new file and you need to call it in every HTML file so that it would be displayed as a footer
now doha listen up, what we need are a few things:
1-in the online application there will be a "" statement below "Part Time attendance : Three days a week, please specify the days in the box below" this line, i want you to use javascript to make sure that WHEN the user ticks that radio button a set of combo boxes would appear with the days written next to them (i've already used a combobox so jst copy paste mine and change names obv)  so that the user is allowed to choose the customized days BUT if the users happens to tick another radio button automatically ,given thats its a radio button, the one with the customized days will be deselected and on which note i want the set of comboboxes to disappear

2- i also want you to manage the whole WHICH PAGE GOES TO WHAT PAGE thing, simple you can do that in html, javascript and php but javascript can be way faster than the other 2

3-in the online application there will be a "" statement below "Relation" statement, i want you to create a drop-down-list containing average familial relations like (aunt, uncle) that way we can limit any varying entries

CSS TIME:

1-in every page no matter what i want CSS appropriate for children or child-friendly
2- logo has to be on the top right or left whichever u find to be better
3-i want the paragraph written below "WELCOME" in the welcome page to be in the middle of the screen (not aligned to center but actually in the middle of the screen) that way you can have high opacity background containing children pictures (extracted from their facebook) from the sides where parents can visibly see the children background from the sides and in the middle there square box thing that contains the text where you can still see the children pictures but with even high opacity (they don't have to be clear but visible enuff jst for css effect, call me if you need more explanation)
4- in contactus.php file theres a statement "" pretty self explanatory we jst need their facebook link in the footer with everything else

GOOD LUCK this is due 26th of feb, to be delivered on the 27th of feb

**Comment by daizy96** [comment]
by now all the JS part is done
